site_name: Programming-Kubernetes中文文档
site_url: https://github.com/xiaoyuaiheshui/Programming-Kubernetes/
repo_url: https://github.com/xiaoyuaiheshui/Programming-Kubernetes/
site_description: 'Programming-Kubernetes中文文档'

site_author: xiaoyuaiheshui
copyright: 714545064@qq.com

theme: readthedocs

pages:
  - 欢迎: index.md
  - 简介: 00-前言.md

markdown_extensions:
  - extra
  - tables
  - toc:
      permalink: True
  - fenced_code
  - smarty
  - mdx_math:
      enable_dollar_delimiter: True
  - footnotes